### ISSUE TITLE
uninitialized constant Faraday::Error::ClientError

### ISSUE THREAD

**Issue by earnold** [fulcrumapp/fulcrum-ruby#30]
Hi there,

I just added this gem to my rails app. When I try to start a Rails console, I get this message: 

```
 uninitialized constant Faraday::Error::ClientError
Did you mean?  Faraday::ClientError (NameError)
```

When a stack trace that traces back to these lines: 
```
	from .../gems/fulcrum-0.1.5/lib/fulcrum/api.rb:6:in `<module:Fulcrum>'
	from .../gems/fulcrum-0.1.5/lib/fulcrum/api.rb:4:in `<main>'
```

Any idea how I can resolve this?

**Comment by zhm** [comment]
`0.9.0` is now published with updated dependencies
